language: php

php:
    - 7.3
    - 7.4
    - 8.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source

script:
    - phpunit

after_success:
    - if    [ $TRAVIS_PHP_VERSION = '7.3' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh generate-api.sh; fi
